config/routes.rb
Rails.application.routes.draw do
  root "diaries#index"
  resources :diaries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  has_many :records, dependent: :destroy

  # 画像投稿機能のActiveStorageでの書き方
  has_one_attached :image

  # ActiveStorageのバリデーション実装
  # validate :image_type

  private

  def image_type
    if !image.blob.content_type.in?(%('image/jpeg image/png'))
      image.purge #rails6では必要ない
      errors.add(:image, 'ははJPEGまたはPNG形式を選択してアップロードしてください')
    end
  end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :diary
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def new
    @diary = PostDiary.new
  end

  def index
    @diaries = Diary.all
  end

  def show
    @diary = Diary.find(params[:id])
  end

  def edit
    @diary = Diary.find(params[:id])
  end

  def create
    @diary = PostDiary.new(diary_params)
    if @diary.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update

  end

  def delete

  end

  private

  def diary_params
    params.require(:post_diary).permit(:title, :image, :text)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/index.html.erb
<div class="btn">
  <%= link_to "日記を作成する", new_diary_path %>
</div>
<div class="index">
  <% @diaries.each do |diary| %>
    <div class="content">
      <%= link_to diary_path(diary) do %>
        <%= diary.title %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/diaries/new.html.erb
<%= form_with model: @diary, url: diaries_path, local: true do |f| %>
  <div class="field post-image">
    <div class="post-image-title">
      <%= f.label :今日の画像 %>
    </div>
    <div class="post-image-form">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="field post-date">
    <div class="post-date-title">
      <%= f.label :今日の日付 %>
    </div>
    <div class="post-date-form">
      <%= f.text_field :title %>
    </div>
  </div>

  <div id="form_area">
    <div>
      <%= f.label :今日やったこと %>
    </div>
    <div>
      <%= f.text_field :text, id: "inputform_0", placeholder: "フォーム-0" %>
    </div>
  </div>

  <input type="button" value="フォーム追加" onclick="addForm()">


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diaries/show.html.erb
<div>
  <% if @diary.image.attached? %>
    <%= image_tag @diary.image.variant(resize:'100x100') %>
  <% end %>
  <%= @diary.title %>
  <% @diary.records.each do |record| %>
    <%= record.text %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormObjectPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice" class="ml-5 mt-3"><%= notice %></p>
    <p id="alert" class="ml-5 mt-3"><%= alert %></p>
    <%= yield %>
  </body>
</html>